
// This file has been generated by the GUI designer. Do not modify.
namespace GUI
{
	public partial class AddItem
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.Image image1;
		private global::Gtk.Table table2;
		private global::Gtk.Entry entAddItemDescription;
		private global::Gtk.Entry entAddItemId;
		private global::Gtk.Entry entAddItemMaxStock;
		private global::Gtk.Entry entAddItemMinStock;
		private global::Gtk.Entry entAddItemStock;
		private global::Gtk.Label lblAddItemDescription;
		private global::Gtk.Label lblAddItemId;
		private global::Gtk.Label lblAddItemMaxStock;
		private global::Gtk.Label lblAddItemMinStock;
		private global::Gtk.Label lblAddItemStockInicial;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Button btnAddItemOk;
		private global::Gtk.Button btnAddItemCancel;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget GUI.AddItem
			this.Name = "GUI.AddItem";
			this.Title = global::Mono.Unix.Catalog.GetString ("Agregar nuevo articulo");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child GUI.AddItem.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.image1 = new global::Gtk.Image ();
			this.image1.Name = "image1";
			this.vbox2.Add (this.image1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.image1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.table2 = new global::Gtk.Table (((uint)(5)), ((uint)(2)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.entAddItemDescription = new global::Gtk.Entry ();
			this.entAddItemDescription.CanFocus = true;
			this.entAddItemDescription.Name = "entAddItemDescription";
			this.entAddItemDescription.IsEditable = true;
			this.entAddItemDescription.InvisibleChar = '●';
			this.table2.Add (this.entAddItemDescription);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table2 [this.entAddItemDescription]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.entAddItemId = new global::Gtk.Entry ();
			this.entAddItemId.CanFocus = true;
			this.entAddItemId.Name = "entAddItemId";
			this.entAddItemId.IsEditable = true;
			this.entAddItemId.InvisibleChar = '●';
			this.table2.Add (this.entAddItemId);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table2 [this.entAddItemId]));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.entAddItemMaxStock = new global::Gtk.Entry ();
			this.entAddItemMaxStock.CanFocus = true;
			this.entAddItemMaxStock.Name = "entAddItemMaxStock";
			this.entAddItemMaxStock.IsEditable = true;
			this.entAddItemMaxStock.InvisibleChar = '●';
			this.table2.Add (this.entAddItemMaxStock);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table2 [this.entAddItemMaxStock]));
			w4.TopAttach = ((uint)(4));
			w4.BottomAttach = ((uint)(5));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.entAddItemMinStock = new global::Gtk.Entry ();
			this.entAddItemMinStock.CanFocus = true;
			this.entAddItemMinStock.Name = "entAddItemMinStock";
			this.entAddItemMinStock.IsEditable = true;
			this.entAddItemMinStock.InvisibleChar = '●';
			this.table2.Add (this.entAddItemMinStock);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table2 [this.entAddItemMinStock]));
			w5.TopAttach = ((uint)(3));
			w5.BottomAttach = ((uint)(4));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.entAddItemStock = new global::Gtk.Entry ();
			this.entAddItemStock.CanFocus = true;
			this.entAddItemStock.Name = "entAddItemStock";
			this.entAddItemStock.IsEditable = true;
			this.entAddItemStock.InvisibleChar = '●';
			this.table2.Add (this.entAddItemStock);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table2 [this.entAddItemStock]));
			w6.TopAttach = ((uint)(2));
			w6.BottomAttach = ((uint)(3));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.lblAddItemDescription = new global::Gtk.Label ();
			this.lblAddItemDescription.Name = "lblAddItemDescription";
			this.lblAddItemDescription.LabelProp = global::Mono.Unix.Catalog.GetString ("Descripcion");
			this.table2.Add (this.lblAddItemDescription);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table2 [this.lblAddItemDescription]));
			w7.TopAttach = ((uint)(1));
			w7.BottomAttach = ((uint)(2));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.lblAddItemId = new global::Gtk.Label ();
			this.lblAddItemId.Name = "lblAddItemId";
			this.lblAddItemId.LabelProp = global::Mono.Unix.Catalog.GetString ("ID");
			this.table2.Add (this.lblAddItemId);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table2 [this.lblAddItemId]));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.lblAddItemMaxStock = new global::Gtk.Label ();
			this.lblAddItemMaxStock.Name = "lblAddItemMaxStock";
			this.lblAddItemMaxStock.LabelProp = global::Mono.Unix.Catalog.GetString ("S.Maximo");
			this.table2.Add (this.lblAddItemMaxStock);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table2 [this.lblAddItemMaxStock]));
			w9.TopAttach = ((uint)(4));
			w9.BottomAttach = ((uint)(5));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.lblAddItemMinStock = new global::Gtk.Label ();
			this.lblAddItemMinStock.Name = "lblAddItemMinStock";
			this.lblAddItemMinStock.LabelProp = global::Mono.Unix.Catalog.GetString ("S.Minimo");
			this.table2.Add (this.lblAddItemMinStock);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table2 [this.lblAddItemMinStock]));
			w10.TopAttach = ((uint)(3));
			w10.BottomAttach = ((uint)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.lblAddItemStockInicial = new global::Gtk.Label ();
			this.lblAddItemStockInicial.Name = "lblAddItemStockInicial";
			this.lblAddItemStockInicial.LabelProp = global::Mono.Unix.Catalog.GetString ("Stock");
			this.table2.Add (this.lblAddItemStockInicial);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table2 [this.lblAddItemStockInicial]));
			w11.TopAttach = ((uint)(2));
			w11.BottomAttach = ((uint)(3));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox2.Add (this.table2);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.table2]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 3;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnAddItemOk = new global::Gtk.Button ();
			this.btnAddItemOk.CanFocus = true;
			this.btnAddItemOk.Name = "btnAddItemOk";
			this.btnAddItemOk.UseUnderline = true;
			this.btnAddItemOk.BorderWidth = ((uint)(3));
			this.btnAddItemOk.Label = global::Mono.Unix.Catalog.GetString ("Aceptar");
			this.hbox1.Add (this.btnAddItemOk);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnAddItemOk]));
			w13.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnAddItemCancel = new global::Gtk.Button ();
			this.btnAddItemCancel.CanFocus = true;
			this.btnAddItemCancel.Name = "btnAddItemCancel";
			this.btnAddItemCancel.UseUnderline = true;
			this.btnAddItemCancel.BorderWidth = ((uint)(3));
			this.btnAddItemCancel.Label = global::Mono.Unix.Catalog.GetString ("Cancelar");
			this.hbox1.Add (this.btnAddItemCancel);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnAddItemCancel]));
			w14.Position = 1;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w15.Position = 2;
			w15.Expand = false;
			w15.Fill = false;
			w15.Padding = ((uint)(10));
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 348;
			this.DefaultHeight = 301;
			this.Show ();
			this.btnAddItemOk.Clicked += new global::System.EventHandler (this.OnBtnAddItemOkClicked);
		}
	}
}
