
// This file has been generated by the GUI designer. Do not modify.
namespace GUI
{
	public partial class StockAdmin
	{
		private global::Gtk.Frame frame2;
		private global::Gtk.HPaned hpaned2;
		private global::Gtk.HBox hbox3;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView textview5;
		private global::Gtk.VBox vbox6;
		private global::Gtk.Image image1;
		private global::Gtk.HBox hbox4;
		private global::Gtk.Label lblDepositoSeleccionadoMensaje;
		private global::Gtk.Label lblDepositoSeleccionado;
		private global::Gtk.Button btnBackToWareHouseSelect;
		private global::Gtk.Table table2;
		private global::Gtk.Button btnAddArticle;
		private global::Gtk.Button btnDeleteArticle;
		private global::Gtk.Button btnDischargeArticle;
		private global::Gtk.Button btnEntryArticle;
		private global::Gtk.Label GtkLabel1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget GUI.StockAdmin
			this.Name = "GUI.StockAdmin";
			this.Title = global::Mono.Unix.Catalog.GetString ("StockAdmin");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child GUI.StockAdmin.Gtk.Container+ContainerChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame2.Gtk.Container+ContainerChild
			this.hpaned2 = new global::Gtk.HPaned ();
			this.hpaned2.CanFocus = true;
			this.hpaned2.Name = "hpaned2";
			// Container child hpaned2.Gtk.Paned+PanedChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textview5 = new global::Gtk.TextView ();
			this.textview5.CanFocus = true;
			this.textview5.Name = "textview5";
			this.GtkScrolledWindow.Add (this.textview5);
			this.hbox3.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.GtkScrolledWindow]));
			w2.Position = 0;
			this.hpaned2.Add (this.hbox3);
			global::Gtk.Paned.PanedChild w3 = ((global::Gtk.Paned.PanedChild)(this.hpaned2 [this.hbox3]));
			w3.Resize = false;
			// Container child hpaned2.Gtk.Paned+PanedChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.image1 = new global::Gtk.Image ();
			this.image1.Name = "image1";
			this.vbox6.Add (this.image1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.image1]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.lblDepositoSeleccionadoMensaje = new global::Gtk.Label ();
			this.lblDepositoSeleccionadoMensaje.Name = "lblDepositoSeleccionadoMensaje";
			this.lblDepositoSeleccionadoMensaje.LabelProp = global::Mono.Unix.Catalog.GetString ("Trabajando en Deposito:");
			this.hbox4.Add (this.lblDepositoSeleccionadoMensaje);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.lblDepositoSeleccionadoMensaje]));
			w5.Position = 0;
			w5.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.lblDepositoSeleccionado = new global::Gtk.Label ();
			this.lblDepositoSeleccionado.Name = "lblDepositoSeleccionado";
			this.lblDepositoSeleccionado.LabelProp = global::Mono.Unix.Catalog.GetString ("EMPRESA");
			this.hbox4.Add (this.lblDepositoSeleccionado);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.lblDepositoSeleccionado]));
			w6.Position = 1;
			w6.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.btnBackToWareHouseSelect = new global::Gtk.Button ();
			this.btnBackToWareHouseSelect.CanFocus = true;
			this.btnBackToWareHouseSelect.Name = "btnBackToWareHouseSelect";
			this.btnBackToWareHouseSelect.UseUnderline = true;
			this.btnBackToWareHouseSelect.Label = global::Mono.Unix.Catalog.GetString ("...");
			this.hbox4.Add (this.btnBackToWareHouseSelect);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.btnBackToWareHouseSelect]));
			w7.Position = 2;
			w7.Fill = false;
			this.vbox6.Add (this.hbox4);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox4]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.table2 = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(25));
			this.table2.ColumnSpacing = ((uint)(30));
			this.table2.BorderWidth = ((uint)(20));
			// Container child table2.Gtk.Table+TableChild
			this.btnAddArticle = new global::Gtk.Button ();
			this.btnAddArticle.CanFocus = true;
			this.btnAddArticle.Name = "btnAddArticle";
			this.btnAddArticle.UseUnderline = true;
			this.btnAddArticle.Label = global::Mono.Unix.Catalog.GetString ("CREAR ARTICULO");
			this.table2.Add (this.btnAddArticle);
			// Container child table2.Gtk.Table+TableChild
			this.btnDeleteArticle = new global::Gtk.Button ();
			this.btnDeleteArticle.CanFocus = true;
			this.btnDeleteArticle.Name = "btnDeleteArticle";
			this.btnDeleteArticle.UseUnderline = true;
			this.btnDeleteArticle.Label = global::Mono.Unix.Catalog.GetString ("BORRAR ARTICULO");
			this.table2.Add (this.btnDeleteArticle);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table2 [this.btnDeleteArticle]));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			// Container child table2.Gtk.Table+TableChild
			this.btnDischargeArticle = new global::Gtk.Button ();
			this.btnDischargeArticle.CanFocus = true;
			this.btnDischargeArticle.Name = "btnDischargeArticle";
			this.btnDischargeArticle.UseUnderline = true;
			this.btnDischargeArticle.Label = global::Mono.Unix.Catalog.GetString ("EGRESO");
			this.table2.Add (this.btnDischargeArticle);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table2 [this.btnDischargeArticle]));
			w11.TopAttach = ((uint)(1));
			w11.BottomAttach = ((uint)(2));
			w11.LeftAttach = ((uint)(1));
			w11.RightAttach = ((uint)(2));
			// Container child table2.Gtk.Table+TableChild
			this.btnEntryArticle = new global::Gtk.Button ();
			this.btnEntryArticle.CanFocus = true;
			this.btnEntryArticle.Name = "btnEntryArticle";
			this.btnEntryArticle.UseUnderline = true;
			this.btnEntryArticle.Label = global::Mono.Unix.Catalog.GetString ("INGRESO");
			this.table2.Add (this.btnEntryArticle);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table2 [this.btnEntryArticle]));
			w12.TopAttach = ((uint)(1));
			w12.BottomAttach = ((uint)(2));
			this.vbox6.Add (this.table2);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.table2]));
			w13.Position = 2;
			this.hpaned2.Add (this.vbox6);
			this.frame2.Add (this.hpaned2);
			this.GtkLabel1 = new global::Gtk.Label ();
			this.GtkLabel1.Name = "GtkLabel1";
			this.GtkLabel1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>GtkFrame</b>");
			this.GtkLabel1.UseMarkup = true;
			this.frame2.LabelWidget = this.GtkLabel1;
			this.Add (this.frame2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 649;
			this.DefaultHeight = 384;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		}
	}
}
