
// This file has been generated by the GUI designer. Do not modify.
namespace GUI
{
	public partial class RemoveItem
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget GUI.RemoveItem
			this.Name = "GUI.RemoveItem";
			this.Title = global::Mono.Unix.Catalog.GetString ("RemoveItem");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
