
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.VBox vbox5;
	private global::Gtk.Label lblMWDeposito;
	private global::Gtk.HBox hbox2;
	private global::Gtk.Button btnMWBiyemas;
	private global::Gtk.Button btnMWKandiko;
	private global::Gtk.Button btnMWRebisco;

	bool AllowGrow;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.CanDefault = true;
		this.CanFocus = true;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Stock AGG Sistemas");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		this.Resizable = false;
		this.AllowGrow = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox5 = new global::Gtk.VBox ();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.lblMWDeposito = new global::Gtk.Label ();
		this.lblMWDeposito.Name = "lblMWDeposito";
		this.lblMWDeposito.LabelProp = global::Mono.Unix.Catalog.GetString ("SELECCIONE DEPOSITO");
		this.lblMWDeposito.Justify = ((global::Gtk.Justification)(2));
		this.vbox5.Add (this.lblMWDeposito);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.lblMWDeposito]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		w1.Padding = ((uint)(3));
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		this.hbox2.BorderWidth = ((uint)(10));
		// Container child hbox2.Gtk.Box+BoxChild
		this.btnMWBiyemas = new global::Gtk.Button ();
		this.btnMWBiyemas.CanFocus = true;
		this.btnMWBiyemas.Name = "btnMWBiyemas";
		this.btnMWBiyemas.UseUnderline = true;
		this.btnMWBiyemas.BorderWidth = ((uint)(2));
		this.btnMWBiyemas.Label = global::Mono.Unix.Catalog.GetString ("Biyemas");
		this.hbox2.Add (this.btnMWBiyemas);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.btnMWBiyemas]));
		w2.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.btnMWKandiko = new global::Gtk.Button ();
		this.btnMWKandiko.CanFocus = true;
		this.btnMWKandiko.Name = "btnMWKandiko";
		this.btnMWKandiko.UseUnderline = true;
		this.btnMWKandiko.BorderWidth = ((uint)(2));
		this.btnMWKandiko.Label = global::Mono.Unix.Catalog.GetString ("Kandiko");
		this.hbox2.Add (this.btnMWKandiko);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.btnMWKandiko]));
		w3.Position = 1;
		// Container child hbox2.Gtk.Box+BoxChild
		this.btnMWRebisco = new global::Gtk.Button ();
		this.btnMWRebisco.CanFocus = true;
		this.btnMWRebisco.Name = "btnMWRebisco";
		this.btnMWRebisco.UseUnderline = true;
		this.btnMWRebisco.BorderWidth = ((uint)(2));
		this.btnMWRebisco.Label = global::Mono.Unix.Catalog.GetString ("Rebisco");
		this.hbox2.Add (this.btnMWRebisco);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.btnMWRebisco]));
		w4.Position = 2;
		this.vbox5.Add (this.hbox2);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox2]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		this.Add (this.vbox5);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 243;
		this.DefaultHeight = 109;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btnMWBiyemas.Clicked += new global::System.EventHandler (this.OnBtnMWBiyemasClicked);
		this.btnMWKandiko.Clicked += new global::System.EventHandler (this.OnBtnMWKandikoClicked);
		this.btnMWRebisco.Clicked += new global::System.EventHandler (this.OnBtnMWRebiscoClicked);
	}
}
